services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: portscan
      POSTGRES_USER: scanner
      POSTGRES_PASSWORD: scannerpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: